[options]
; This is the password that allows database operations:
; admin_passwd = admin
; dbfilter = .* 

db_host = False
db_port = False
db_user = odoo
db_password = False
addons_path = ./addons, ./custom_addons

xmlrpc_port = 8069

